stages:
  prepare:
    cmd: python src/preprocessing.py
    deps:
      - data/MrBeast_youtube_stats.csv
      - src/preprocessing.py
    outs:
      - data/mrbeast_pipeline.pkl
      - data/processed_mrbeast_train.csv
      - data/processed_mrbeast_test.csv
    params:
      - split.test_size
      - split.random_state